version: '3.8'  # `version`フィールドを `3.8` に更新

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/product-register'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'  # スーパーユーザーのパスワードを設定
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:15-bullseye
    environment:
      - 'POSTGRES_PASSWORD=password'  # スーパーユーザーのパスワードを設定
    volumes:
      - 'db-data:/var/lib/postgresql/data'

volumes:
  db-data:
