version: '3.8'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/product-register'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'  # スーパーユーザーのパスワードを設定
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - 'POSTGRES_PASSWORD=password'  # スーパーユーザーのパスワードを設定
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    volumes:
      - 'db-data:/var/lib/postgresql/data'

volumes:
  db-data:

